// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TalentManagement.Infrastructure.Persistence;

#nullable disable

namespace TalentManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260709140406_ReestructurarFichaColaborador")]
    partial class ReestructurarFichaColaborador
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TalentManagement.Domain.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JefeId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JefeId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CamposModificados")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<string>("ColaboradorNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntidadId")
                        .HasColumnType("int");

                    b.Property<string>("EntidadNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntidadTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Capacitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<byte[]>("ArchivoDocxCertificado")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("ArchivoFirmaCertificado")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("ArchivoPreviewCertificado")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<int?>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DuracionHoras")
                        .HasColumnType("int");

                    b.Property<bool>("EmiteCertificado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Finalizada")
                        .HasColumnType("bit");

                    b.Property<double?>("FirmaAlto")
                        .HasColumnType("float");

                    b.Property<double?>("FirmaAncho")
                        .HasColumnType("float");

                    b.Property<double?>("FirmaX")
                        .HasColumnType("float");

                    b.Property<double?>("FirmaY")
                        .HasColumnType("float");

                    b.Property<string>("MotivoFinalizacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCertificado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlantillaNombreCertificado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Publicada")
                        .HasColumnType("bit");

                    b.Property<string>("TipoArchivoCertificado")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("ColaboradorId");

                    b.ToTable("Capacitaciones");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Certificado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("CapacitacionId")
                        .HasColumnType("int");

                    b.Property<string>("CertificateCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneratedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PdfBytes")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PdfFileKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CapacitacionId");

                    b.HasIndex("ColaboradorId");

                    b.ToTable("Certificados");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.CertificadoEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CertificadoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CertificadoId");

                    b.ToTable("CertificadoEventos");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Colaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<decimal?>("AuxMediosTransporte")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CargoId")
                        .HasColumnType("int");

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ComisionCobros")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ComisionVentas")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("FechaExpedicion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaIngresoContrato")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LugarNacimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SubTransporte")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SueldoBasico")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoContrato")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("CargoId");

                    b.HasIndex("Email")
                        .HasFilter("[Activo] = 1");

                    b.ToTable("Colaboradores");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.ColaboradorCampoDefinicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CampoClave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<bool>("Requerido")
                        .HasColumnType("bit");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ColaboradorCampoDefiniciones");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.ColaboradorCampoValor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("ColaboradorCampoDefinicionId")
                        .HasColumnType("int");

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorCampoDefinicionId");

                    b.HasIndex("ColaboradorId", "ColaboradorCampoDefinicionId")
                        .IsUnique();

                    b.ToTable("ColaboradorCampoValores");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Cuestionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("AprobacionPorCorrectas")
                        .HasColumnType("bit");

                    b.Property<int>("CapacitacionId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IntentosPermitidos")
                        .HasColumnType("int");

                    b.Property<int>("MinCorrectas")
                        .HasColumnType("int");

                    b.Property<int>("PuntajeAprobacion")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CapacitacionId");

                    b.ToTable("Cuestionarios");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SharePointItemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SharePointUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.DocumentoControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("AprobadorId")
                        .HasColumnType("int");

                    b.Property<string>("ArchivoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComentarioCambio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatosPersonalizados")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionDetallada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisposicionFinal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DocumentoOriginalId")
                        .HasColumnType("int");

                    b.Property<int?>("EditorId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaDocumento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("ListadoMaestroId")
                        .HasColumnType("int");

                    b.Property<string>("MotivoCambio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OneDriveItemId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OneDriveUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcesoResponsable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proteccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recuperacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SolicitanteId")
                        .HasColumnType("int");

                    b.Property<string>("TiempoRetencion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AprobadorId");

                    b.HasIndex("AreaId");

                    b.HasIndex("DocumentoOriginalId");

                    b.HasIndex("EditorId");

                    b.HasIndex("Estado");

                    b.HasIndex("ListadoMaestroId");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("DocumentosControl");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.DocumentoControlCampoDefinicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CampoClave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsPredeterminado")
                        .HasColumnType("bit");

                    b.Property<int>("ListadoMaestroId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpcionesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<bool>("Requerido")
                        .HasColumnType("bit");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ListadoMaestroId");

                    b.ToTable("DocumentoControlCampoDefiniciones");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.FlujoAprobacionDoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("int");

                    b.Property<string>("EstadoAnterior")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaTransicion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("DocumentoId");

                    b.ToTable("FlujosAprobacionDoc");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("Asistio")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Calificacion")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("CapacitacionId")
                        .HasColumnType("int");

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecursosVistos")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CapacitacionId");

                    b.HasIndex("ColaboradorId");

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.ListadoMaestro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ListadosMaestros");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.ListadoMaestroPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<int?>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<int>("ListadoMaestroId")
                        .HasColumnType("int");

                    b.Property<bool>("PuedeAprobar")
                        .HasColumnType("bit");

                    b.Property<bool>("PuedeEditar")
                        .HasColumnType("bit");

                    b.Property<bool>("PuedeVer")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("ListadoMaestroId", "AreaId")
                        .IsUnique()
                        .HasFilter("[AreaId] IS NOT NULL");

                    b.HasIndex("ListadoMaestroId", "ColaboradorId")
                        .IsUnique()
                        .HasFilter("[ColaboradorId] IS NOT NULL");

                    b.ToTable("ListadoMaestroPermisos");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.OpcionRespuesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("EsCorrecta")
                        .HasColumnType("bit");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("PreguntaId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaId");

                    b.ToTable("OpcionesRespuesta");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.PlantillaDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("AplicaTodasAreas")
                        .HasColumnType("bit");

                    b.Property<byte[]>("ArchivoDocxLegacy")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("ArchivoDocx");

                    b.Property<string>("CamposFormulario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoFirmante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContenidoHtml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocxFileKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirmaImagenBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreFirmante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoPlantilla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VariablesEditables")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlantillasDocumento");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.PlantillaDocumentoArea", b =>
                {
                    b.Property<int>("PlantillaDocumentoId")
                        .HasColumnType("int");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.HasKey("PlantillaDocumentoId", "AreaId");

                    b.HasIndex("AreaId");

                    b.ToTable("PlantillaDocumentoAreas");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Pregunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CuestionarioId")
                        .HasColumnType("int");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CuestionarioId");

                    b.ToTable("Preguntas");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.PropuestaModificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AprobadorId")
                        .HasColumnType("int");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("int");

                    b.Property<string>("EstadoPropuesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoRechazo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SharePointItemIdPropuesta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AprobadorId");

                    b.HasIndex("AreaId");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("DocumentoId");

                    b.ToTable("PropuestasModificacion");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.RecursoCapacitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CapacitacionId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CapacitacionId");

                    b.ToTable("RecursosCapacitacion");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.RespuestaCuestionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("Aprobado")
                        .HasColumnType("bit");

                    b.Property<int>("CuestionarioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<int>("InscripcionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Puntaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TotalCorrectas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CuestionarioId");

                    b.HasIndex("InscripcionId");

                    b.ToTable("RespuestasCuestionario");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.RespuestaPregunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("OpcionElegidaId")
                        .HasColumnType("int");

                    b.Property<int>("PreguntaId")
                        .HasColumnType("int");

                    b.Property<int>("RespuestaCuestionarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OpcionElegidaId");

                    b.HasIndex("PreguntaId");

                    b.HasIndex("RespuestaCuestionarioId");

                    b.ToTable("RespuestasPregunta");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.SolicitudCambioDocumentoControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AprobadorId")
                        .HasColumnType("int");

                    b.Property<int?>("BorradorDocumentoId")
                        .HasColumnType("int");

                    b.Property<string>("ComentarioResolucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComentarioSolicitud")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatosOriginales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatosPropuestos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionDetallada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentoControlId")
                        .HasColumnType("int");

                    b.Property<int?>("EditorId")
                        .HasColumnType("int");

                    b.Property<string>("EstadoPropuesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEdicion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRevision")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoCambio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacionesRevision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RevisorId")
                        .HasColumnType("int");

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AprobadorId");

                    b.HasIndex("BorradorDocumentoId");

                    b.HasIndex("DocumentoControlId");

                    b.HasIndex("EditorId");

                    b.HasIndex("EstadoPropuesta");

                    b.HasIndex("RevisorId");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("SolicitudesCambioDocumentoControl");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.SolicitudDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<string>("ComentarioAdmin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Descargado")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NotificadoColaborador")
                        .HasColumnType("bit");

                    b.Property<byte[]>("PdfBytes")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PdfFileKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantillaDocumentoId")
                        .HasColumnType("int");

                    b.Property<string>("VariablesCompletadas")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("Estado")
                        .HasFilter("[Activo] = 1");

                    b.HasIndex("PlantillaDocumentoId");

                    b.ToTable("SolicitudesDocumento");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.VersionDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SharePointItemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.ToTable("VersionesDocumento");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Area", b =>
                {
                    b.HasOne("TalentManagement.Domain.Entities.Colaborador", "Jefe")
                        .WithMany()
                        .HasForeignKey("JefeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Jefe");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("TalentManagement.Domain.Entities.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Capacitacion", b =>
                {
                    b.HasOne("TalentManagement.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId");

                    b.HasOne("TalentManagement.Domain.Entities.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId");

                    b.Navigation("Area");

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Cargo", b =>
                {
                    b.HasOne("TalentManagement.Domain.Entities.Area", "Area")
                        .WithMany("Cargos")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Certificado", b =>
                {
                    b.HasOne("TalentManagement.Domain.Entities.Capacitacion", "Capacitacion")
                        .WithMany()
                        .HasForeignKey("CapacitacionId");

                    b.HasOne("TalentManagement.Domain.Entities.Colaborador", "Colaborador")
                        .WithMany("Certificados")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capacitacion");

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.CertificadoEvento", b =>
                {
                    b.HasOne("TalentManagement.Domain.Entities.Certificado", "Certificado")
                        .WithMany("Eventos")
                        .HasForeignKey("CertificadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificado");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Colaborador", b =>
                {
                    b.HasOne("TalentManagement.Domain.Entities.Area", "Area")
                        .WithMany("Colaboradores")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TalentManagement.Domain.Entities.Cargo", "Cargo")
                        .WithMany("Colaboradores")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.ColaboradorCampoValor", b =>
                {
                    b.HasOne("TalentManagement.Domain.Entities.ColaboradorCampoDefinicion", "ColaboradorCampoDefinicion")
                        .WithMany("Valores")
                        .HasForeignKey("ColaboradorCampoDefinicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalentManagement.Domain.Entities.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("ColaboradorCampoDefinicion");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Cuestionario", b =>
                {
                    b.HasOne("TalentManagement.Domain.Entities.Capacitacion", "Capacitacion")
                        .WithMany()
                        .HasForeignKey("CapacitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capacitacion");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Documento", b =>
                {
                    b.HasOne("TalentManagement.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.DocumentoControl", b =>
                {
                    b.HasOne("TalentManagement.Domain.Entities.Colaborador", "Aprobador")
                        .WithMany()
                        .HasForeignKey("AprobadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TalentManagement.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TalentManagement.Domain.Entities.DocumentoControl", "DocumentoOriginal")
                        .WithMany()
                        .HasForeignKey("DocumentoOriginalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TalentManagement.Domain.Entities.Colaborador", "Editor")
                        .WithMany()
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TalentManagement.Domain.Entities.ListadoMaestro", "ListadoMaestro")
                        .WithMany("Documentos")
                        .HasForeignKey("ListadoMaestroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TalentManagement.Domain.Entities.Colaborador", "Solicitante")
                        .WithMany()
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Aprobador");

                    b.Navigation("Area");

                    b.Navigation("DocumentoOriginal");

                    b.Navigation("Editor");

                    b.Navigation("ListadoMaestro");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.DocumentoControlCampoDefinicion", b =>
                {
                    b.HasOne("TalentManagement.Domain.Entities.ListadoMaestro", "ListadoMaestro")
                        .WithMany("Campos")
                        .HasForeignKey("ListadoMaestroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListadoMaestro");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.FlujoAprobacionDoc", b =>
                {
                    b.HasOne("TalentManagement.Domain.Entities.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TalentManagement.Domain.Entities.Documento", "Documento")
                        .WithMany("FlujoAprobacion")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Inscripcion", b =>
                {
                    b.HasOne("TalentManagement.Domain.Entities.Capacitacion", "Capacitacion")
                        .WithMany("Inscripciones")
                        .HasForeignKey("CapacitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalentManagement.Domain.Entities.Colaborador", "Colaborador")
                        .WithMany("Inscripciones")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capacitacion");

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.ListadoMaestroPermiso", b =>
                {
                    b.HasOne("TalentManagement.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TalentManagement.Domain.Entities.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TalentManagement.Domain.Entities.ListadoMaestro", "ListadoMaestro")
                        .WithMany("Permisos")
                        .HasForeignKey("ListadoMaestroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Colaborador");

                    b.Navigation("ListadoMaestro");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.OpcionRespuesta", b =>
                {
                    b.HasOne("TalentManagement.Domain.Entities.Pregunta", "Pregunta")
                        .WithMany("Opciones")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.PlantillaDocumentoArea", b =>
                {
                    b.HasOne("TalentManagement.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TalentManagement.Domain.Entities.PlantillaDocumento", "PlantillaDocumento")
                        .WithMany("Areas")
                        .HasForeignKey("PlantillaDocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("PlantillaDocumento");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Pregunta", b =>
                {
                    b.HasOne("TalentManagement.Domain.Entities.Cuestionario", "Cuestionario")
                        .WithMany("Preguntas")
                        .HasForeignKey("CuestionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuestionario");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.PropuestaModificacion", b =>
                {
                    b.HasOne("TalentManagement.Domain.Entities.Colaborador", "Aprobador")
                        .WithMany()
                        .HasForeignKey("AprobadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TalentManagement.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalentManagement.Domain.Entities.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TalentManagement.Domain.Entities.Documento", "Documento")
                        .WithMany("Propuestas")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aprobador");

                    b.Navigation("Area");

                    b.Navigation("Colaborador");

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.RecursoCapacitacion", b =>
                {
                    b.HasOne("TalentManagement.Domain.Entities.Capacitacion", "Capacitacion")
                        .WithMany("Recursos")
                        .HasForeignKey("CapacitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capacitacion");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.RespuestaCuestionario", b =>
                {
                    b.HasOne("TalentManagement.Domain.Entities.Cuestionario", "Cuestionario")
                        .WithMany("Respuestas")
                        .HasForeignKey("CuestionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TalentManagement.Domain.Entities.Inscripcion", "Inscripcion")
                        .WithMany()
                        .HasForeignKey("InscripcionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cuestionario");

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.RespuestaPregunta", b =>
                {
                    b.HasOne("TalentManagement.Domain.Entities.OpcionRespuesta", "OpcionElegida")
                        .WithMany()
                        .HasForeignKey("OpcionElegidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TalentManagement.Domain.Entities.Pregunta", "Pregunta")
                        .WithMany()
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TalentManagement.Domain.Entities.RespuestaCuestionario", "RespuestaCuestionario")
                        .WithMany("Respuestas")
                        .HasForeignKey("RespuestaCuestionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OpcionElegida");

                    b.Navigation("Pregunta");

                    b.Navigation("RespuestaCuestionario");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.SolicitudCambioDocumentoControl", b =>
                {
                    b.HasOne("TalentManagement.Domain.Entities.Colaborador", "Aprobador")
                        .WithMany()
                        .HasForeignKey("AprobadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TalentManagement.Domain.Entities.DocumentoControl", "BorradorDocumento")
                        .WithMany()
                        .HasForeignKey("BorradorDocumentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TalentManagement.Domain.Entities.DocumentoControl", "DocumentoControl")
                        .WithMany()
                        .HasForeignKey("DocumentoControlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TalentManagement.Domain.Entities.Colaborador", "Editor")
                        .WithMany()
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TalentManagement.Domain.Entities.Colaborador", "Revisor")
                        .WithMany()
                        .HasForeignKey("RevisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TalentManagement.Domain.Entities.Colaborador", "Solicitante")
                        .WithMany()
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aprobador");

                    b.Navigation("BorradorDocumento");

                    b.Navigation("DocumentoControl");

                    b.Navigation("Editor");

                    b.Navigation("Revisor");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.SolicitudDocumento", b =>
                {
                    b.HasOne("TalentManagement.Domain.Entities.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TalentManagement.Domain.Entities.PlantillaDocumento", "PlantillaDocumento")
                        .WithMany("Solicitudes")
                        .HasForeignKey("PlantillaDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("PlantillaDocumento");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.VersionDocumento", b =>
                {
                    b.HasOne("TalentManagement.Domain.Entities.Documento", "Documento")
                        .WithMany("Versiones")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Area", b =>
                {
                    b.Navigation("Cargos");

                    b.Navigation("Colaboradores");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Capacitacion", b =>
                {
                    b.Navigation("Inscripciones");

                    b.Navigation("Recursos");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Cargo", b =>
                {
                    b.Navigation("Colaboradores");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Certificado", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Colaborador", b =>
                {
                    b.Navigation("Certificados");

                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.ColaboradorCampoDefinicion", b =>
                {
                    b.Navigation("Valores");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Cuestionario", b =>
                {
                    b.Navigation("Preguntas");

                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Documento", b =>
                {
                    b.Navigation("FlujoAprobacion");

                    b.Navigation("Propuestas");

                    b.Navigation("Versiones");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.ListadoMaestro", b =>
                {
                    b.Navigation("Campos");

                    b.Navigation("Documentos");

                    b.Navigation("Permisos");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.PlantillaDocumento", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.Pregunta", b =>
                {
                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("TalentManagement.Domain.Entities.RespuestaCuestionario", b =>
                {
                    b.Navigation("Respuestas");
                });
#pragma warning restore 612, 618
        }
    }
}
